server:
  port: ${PORT:8090}

logging:
  level:
    com:
      oop:
        client:
          KeycloakClient: DEBUG


spring:
  profiles:
    active: ${APP_PROFILE:dev}
  datasource:
    url: jdbc:postgresql://localhost:5432/payments
    username: carexoid
    password: carexoid
    driver: org.postgresql.Driver
  liquibase:
    change-log: classpath:/db/changelog/db.changeLog-master.xml
    enabled: true
  jpa:
    hibernate:
      ddl-auto: validate
    #show-sql: true
  application:
    name: core

keycloak:
  authServerUrl: http://localhost:8180/auth
  realm: demo
  resource: payments-microservice
  public-client: true
  ssl-required: "none"

keycloak-auth:
  clientSecret: d4230c83-f6f7-472b-95d9-aaec727ca65d
  adminUsername: carexoid
  adminPassword: carexoid